# Generated by Django 4.1.2 on 2022-10-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receitas", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Receita",),
    ]
