# Generated by Django 4.1.2 on 2022-10-25 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("receitas", "0002_delete_receita"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_receita", models.CharField(max_length=200)),
                ("ingredientes", models.TextField()),
                ("tempo_preparo", models.IntegerField()),
                ("rendimento", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=100)),
                (
                    "date_receita",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
